name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTg0ZDNlZmQtYWM2OC00NDUwLTgxOTMtYjc1MzdhNjE0ZDcyIiwidGVuYW50X2lkIjoiMmE4YTUyZjQwYWIyMTViODUyMGI1MjQ0OTg4ZDI5MjdmYzA1M2U3MDkxZTcxYTQyOWUzYzkzMWM5ZTBlOTgyNSIsImludGVybmFsX3NlY3JldCI6Ijg1MjA4YzkzLTBmMzQtNGY2MC1hZjI3LWY2ZTg1YjQyM2NmZSJ9.zooSDrQGb86KDefnI-4l-uRIQI9e3lcN5fxIrq3eT8s"

JWT_KEY="Aaditya"
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1