name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjhiZDA4MjctM2Y5Yi00N2ZmLTk4YWMtYTQyZjYxNGRjMmNjIiwidGVuYW50X2lkIjoiNjA3Yzk2OGNlMmE2MGU4YmIxNTY0NjlkNmYwNzE1YTc1ZDIzYzIyODEyMTQ1ZjU4YTYyNTRkZDY2YzBiYmU2MSIsImludGVybmFsX3NlY3JldCI6IjUyYmZkYWI1LWE5YWQtNGZiNy04MDYzLTkzNGQzZjJiYjQ0MSJ9.SV7A43XY9p4caRhphhDQOcm2OXISMegaoJx6kc7wisQ"
JWT_KEY="Aaditya"
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1